version: "3.8"

services:
  frontend:
    build:
      context: ../cloud-integration-frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
      # - "443:443"  # add TLS later
    networks: [cloud-network]

  backend:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudintegration
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks: [cloud-network]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cloudintegration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudintegration"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks: [cloud-network]

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    networks: [cloud-network]

volumes:
  postgres_data:

networks:
  cloud-network:
    driver: bridge
