# Development Environment Configuration
spring:
  application:
    name: cloud-integration-app
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/cloudintegration_dev
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  # Server Configuration
  server:
    port: 8080
    servlet:
      context-path: /api
      
  # Logging Configuration
  logging:
    level:
      com.example.cloudintegrationapp: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Specific Configuration
app:
  security:
    jwt:
      enabled: false  # Disable JWT in dev for easier testing
    cors:
      allowed-origins: 
        - "http://localhost:4200"
        - "http://localhost:80"
        - "http://localhost"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      
  cloud:
    azure:
      enabled: false
    gcp:
      enabled: false
    splunk:
      enabled: false
      
# Management endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
